name: Update ERA5 dataset
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: era5
          environment-file: .binder/environment.yml
          python-version: 3.8
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list

          mkdir -p ~/.aws
          touch ~/.aws/credentials

          echo "
          [default]
          aws_access_key_id = ${{ secrets.ERA5_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.ERA5_AWS_SECRET_KEY_ID }}
          region = us-east-2
          source_profile = default" > ~/.aws/credentials

          python run.py
